# Site settings
title: Alexander Hansson — webbutvecklare/designer
description: Jag är en frilansande designer/webbutvecklare med erfarenhet från att utveckla siter för bland annat Region Värmland, Brämhults, Folktandvården Värmland & MSC. Min utgångspunkt är Falkenberg, där jag både jobbar i fysiska såväl som virtuella team. Jag tar fram moderna webblösningar till små till mellanstora företag och utvecklar allt från enklare hemsidor till e-handel, bokningssystem och skräddarsydda webbplattformar.
baseurl: ""
url: "https://hnssn.se"
keywords: webbutveckling, webbdesign, design, utveckling, falkenberg, karlstad, alexander, hansson, alexander hansson

address: Storgatan 41, 311 31 Falkenberg
address-google: https://www.google.com/maps/place/Storgatan+41,+311+31+Falkenberg,+Sweden/
email: alexander@hnssn.se
phone: +46 730 66 92 60
available: "true"

# Build settings
permalink: "/portfolio/:title/"
markdown: kramdown
sass:
    style: compressed
exclude:
  - node_modules
